# Site Info
title:              "Coding with Chopsticks"
description:        "Code. Easy as use chopsticks (mostly)"
author_name:        "Odinei Ribeiro" # change this to your name
logo_url:           assets/rice.svg # Get it from GitHub API: https://api.github.com/users/<username>

author:
  email: "odineiramone@gmail.com"
  url: "https://codewithchopsticks.github.io"
  github: "https://github.com/odineiramone"
  telegram: "https://t.me/odineiramone"
  linkedin: "https://br.linkedin.com/in/odineiribeiro"
  twitter: "https://twitter.com/odineiramone"

# Site Settings
url:                https://codingwithchopsticks.github.io # main url
baseurl:            # /
permalink:          /:title # Post permalink
timezone:           America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
