# Site settings
title: Code with Chopsticks
subtitle: Code. Easy as use chopsticks (mostly)
description: "Blog posts about code..."
url: "codewithchopsticks.github.io"
logo: "/img/rice.svg"
image: "/img/rice.svg"
author:
  name: "Odinei Ribeiro"
  email: "odineiramone@gmail.com.com"
  url: "http://codewithchopsticks.github.io"
  github: "http://github.com/odineiramone"
  telegram: "https://t.me/odineiramone"
  linkedin: "https://br.linkedin.com/in/odineiribeiro"
  twitter: "https://twitter.com/odineiramone"

twitter:
  username: odineiramone
  card: summary

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
